export const actionTypes = {
  COIN_LIST_REQUEST: 'COIN_LIST_REQUEST',
  COIN_LIST_RESPONCE: 'COIN_LIST_RESPONCE',
  COIN_LIST_ERROR: 'COIN_LIST_ERROR',
  COIN_ITEM_REQUEST: 'COIN_ITEM_REQUEST',
  COIN_ITEM_RESPONCE: 'COIN_ITEM_RESPONCE',
  COIN_ITEM_ERROR: 'COIN_ITEM_ERROR'
};